[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bump"
version = "1.3.2"
description = "Bumps package version numbers"
readme = "README.rst"
requires-python = ">=3.7"
license = {text = "MIT License"}
authors = [
    { name = "Mark Steve Samson", email = "hello@marksteve.com" }
]
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    "License :: OSI Approved :: MIT License"
]
keywords = ["bump", "increment", "package", "version"]

dependencies = [
    "click>=6,<9",
    "first",
    "packaging>=17.1",
    "toml"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "build",
    "twine"
]

[project.urls]
Homepage = "https://github.com/di/bump"

[project.scripts]
bump = "bump:main"

[tool.setuptools]
zip-safe = false
py-modules = ["bump"]
